# Generated by Django 5.0 on 2023-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_default=models.Value(0.0), decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
