# Generated by Django 5.0 on 2023-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productimage_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideo',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.ManyToManyField(related_name='products', to='product.productvideo'),
        ),
    ]
